FROM continuumio/miniconda3:22.11.1 AS build
COPY knmi-vol-h5-to-odim-h5-dev-user-name-at-domain-com-environment.yaml .

RUN conda config --remove channels defaults || true
RUN conda env update -n venv -f knmi-vol-h5-to-odim-h5-dev-user-name-at-domain-com-environment.yaml
RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM qcdis/python-vol2bird:v2.1.1 AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY knmi-vol-h5-to-odim-h5-dev-user-name-at-domain-com.py .


