FROM jupyter/r-notebook:70178b8e48d7

USER root

RUN R -e "install.packages('optparse', repos='http://cran.rstudio.com')"

RUN mkdir -p /app
COPY read-file-lines-r-dev-user-name-at-domain-com.R /app

